name: we_mail
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  fluttertoast: ^8.0.9
  objectbox: ^1.6.0
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #objectbox
  build_runner: ^2.1.11
  objectbox_generator: any


flutter:


  uses-material-design: true

  